/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package operationgame;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author AIZIK
 */
public class OperationGameUI extends javax.swing.JFrame {
     
    private int num1;
    private int num2;
    private char operation; // Either '+' '-' '*'
    
    private int score;
    private int questionCount;
    
    private static final int GAME_COUNT = 20;
    /**
     * Creates new form OperationGameUI
     */
    
    public void disable(){
        
     startBtn.setEnabled(true);
     jButton2.setEnabled(false);
     jLabel1.setEnabled(false);
     jLabel2.setEnabled(true);
     jLabel4.setEnabled(false);
     jLabel5.setEnabled(false);
     jTextField1.setEnabled(false);
     jlNum1.setEnabled(false);
     jlNum2.setEnabled(false);
     jlOperation.setEnabled(false);
     jlScore.setEnabled(false);
     jtfAnswer.setEnabled(false);
    }
    
    public void enable(){
        
     startBtn.setEnabled(true);
     jButton2.setEnabled(true);
     jLabel1.setEnabled(true);
     jLabel2.setEnabled(true);
     jLabel4.setEnabled(true);
     jLabel5.setEnabled(true);
     jTextField1.setEnabled(true);
     jlNum1.setEnabled(true);
     jlNum2.setEnabled(true);
     jlOperation.setEnabled(true);
     jlScore.setEnabled(true);
     jtfAnswer.setEnabled(true);
    }
    
    public OperationGameUI() {
        initComponents();
        this.setSize(730,500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        disable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jlNum1 = new javax.swing.JLabel();
        jlOperation = new javax.swing.JLabel();
        jlNum2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfAnswer = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(820, 400));
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(222, 188, 236, 0);

        jlNum1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlNum1.setForeground(new java.awt.Color(0, 0, 0));
        jlNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jlNum1);
        jlNum1.setBounds(180, 110, 77, 41);

        jlOperation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlOperation.setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jlOperation);
        jlOperation.setBounds(350, 110, 72, 41);

        jlNum2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlNum2.setForeground(new java.awt.Color(0, 0, 0));
        jlNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jlNum2);
        jlNum2.setBounds(510, 105, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel4.setText("Quiz App");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 20, 109, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ans: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 220, 50, 22);

        jtfAnswer.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jtfAnswer.setToolTipText("Type your answer in here");
        jtfAnswer.setBorder(null);
        jtfAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(jtfAnswer);
        jtfAnswer.setBounds(280, 200, 170, 50);

        startBtn.setBackground(new java.awt.Color(60, 255, 3));
        startBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Start");
        startBtn.setToolTipText("Click to Start or Quit Game");
        startBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn);
        startBtn.setBounds(310, 330, 97, 33);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(java.awt.Color.red);
        jButton2.setText("Enter Result");
        jButton2.setToolTipText("hit to enter your result");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setSelected(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 200, 114, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Score:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 280, 70, 22);

        jlScore.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jlScore.setForeground(new java.awt.Color(255, 51, 0));
        jlScore.setText("0");
        jlScore.setToolTipText("your current score / 20");
        getContentPane().add(jlScore);
        jlScore.setBounds(310, 280, 77, 21);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isaac Ogunleye\\Downloads\\wallpapers\\pexels-photo-377058.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        
        if(evt.getActionCommand().equals("Start")) {
            generateRandomNums();
            startBtn.setText("Quit");
            startBtn.setBackground(Color.red);
            questionCount = 0;
            score = 0;
            enable();
        } else {
            JOptionPane.showMessageDialog(this, "You have Quit the Game With a Score of " + score +" out of " + GAME_COUNT);
            startBtn.setText("Start");
//            btnAction.setAction(null);
        }
        
        if(evt.getActionCommand().equals("Quit")){
            startBtn.setText("Start");
            startBtn.setBackground(Color.green);
            questionCount = 0;
            score = 0; 
            jlScore.setText("0");
            jlNum1.setText("");
            jlNum2.setText("");
            jlOperation.setText("");
            disable();
        }
        
    }//GEN-LAST:event_startBtnActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ans = jtfAnswer.getText();
        if(ans.length() == 0) {
            JOptionPane.showMessageDialog(this, "The Answer cannot be empty");
            return;
        }
        
        try  {
            int answer = Integer.parseInt(ans); 
            int realAnswer;
            if(operation == '+') {
                realAnswer = num1 + num2;
            } else if(operation == '-') {
                realAnswer = num1 - num2;
            } else { // operation = '*'
                realAnswer = num1 * num2;
            }
            
            // iF the user entered the correct answer
            if(realAnswer == answer) {
                JOptionPane.showMessageDialog(this, "Great job !!!!! keep up the good work ", "Correct", JOptionPane.INFORMATION_MESSAGE);
                score += 1;
                jtfAnswer.setText(null);
                jlScore.setText(score+"");
            } else {
                JOptionPane.showMessageDialog(this, " Wrong!!!! The Correct answer is " + realAnswer, "WRONG", JOptionPane.ERROR_MESSAGE);
                jtfAnswer.setText(null);
                jtfAnswer.requestFocus();
                // jtfAnswer.selectAll();
                
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "The value entered is not a valid integeer.... Type in numbers not letters");
            return;
        }
        
        questionCount++;
        
        if(questionCount == GAME_COUNT) {
            JOptionPane.showMessageDialog(this, "The Game has ended. You Got a " + score + " out of " +GAME_COUNT );
            int res = JOptionPane.showConfirmDialog(this, "Do you wany to play again?");
            if(res == JOptionPane.YES_OPTION) {
                generateRandomNums();
                startBtn.setText("Quit");
                jlScore.setText("0");
                questionCount = 0;
                score = 0;
                
                 if(res == JOptionPane.NO_OPTION) {
                     System.exit(0);
                 }
                
                
            } else {
                 startBtn.setText("Start");
                 jtfAnswer.setText(null);
                 jlScore.setText("0");
            }
            return;
        }
        
        generateRandomNums();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnswerActionPerformed
        // TODO add your handling code here:
        jButton2ActionPerformed(evt); // Run the same code for the enter result button
    }//GEN-LAST:event_jtfAnswerActionPerformed

    private void generateRandomNums() {
        num1 = (int) (Math.random() * 10);
        num2 = (int) (Math.random() * 10);
        if (num1 < num2) {
            int swap = num1;
            num1 = num2;
            num2 = swap;
        }
        int rand = (int) (Math.random() * 3);
        if(rand  == 0)
            operation = '+';
        else if(rand  == 1)
            operation = '-';
        else if(rand  == 2 )
            operation = '*';
        
        
        jlNum1.setText(num1 + "");
        jlNum2.setText(num2 + "");
        jlOperation.setText(operation + "");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OperationGameUI().setVisible(true);
                JOptionPane.showMessageDialog(null, "Welcome to Aizik quiz appp. Click start to begin the game!");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlNum1;
    private javax.swing.JLabel jlNum2;
    private javax.swing.JLabel jlOperation;
    private javax.swing.JLabel jlScore;
    private javax.swing.JTextField jtfAnswer;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables

}
